
# Exercise 2.C Working with multiple DataFrames

In [ ]:

import numpy as np
import pandas as pd


## Basic Aggregations

In [ ]:

df_sales['Revenue'] = df_sales['Units_Sold'] * df_sales['Price']
df_sales
data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North'],
    'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
    'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]
}

df_sales = pd.DataFrame(data)
df_sales

In [4]:

df_sales['Revenue'] = df_sales['Units_Sold'] * df_sales['Price']
df_sales

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

In [5]:

total_units = df_sales['Units_Sold'].sum()
total_revenue = df_sales['Revenue'].sum()

total_units, total_revenue

(np.int64(105), np.int64(16000))

In [6]:

avg_units = df_sales['Units_Sold'].mean()
avg_revenue = df_sales['Revenue'].mean()

avg_units, avg_revenue

(np.float64(11.666666666666666), np.float64(1777.7777777777778))

In [ ]:

## Grouping Data

In [8]:
df_sales.groupby('Product')[['Units_Sold', 'Revenue']]

In [9]:
df_sales.groupby('Region')[['Units_Sold', 'Revenue']].mean()

        Units_Sold  Revenue
Region
East     15.000000   2000.0
North    11.666667   1750.0
South    15.000000   2625.0
West      5.000000    750.0

In [11]:
df_sales.groupby(['Product', 'Region'])[['Units_Sold', 'Revenue']].sum

## Sorting and Ranking Data

In [16]:
df_sales.sort_values(by='Units_Sold')

  Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
0       A  North          10    100     1000
4       B  North          10    200     2000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

In [17]:

df_sales.sort_values(by='Revenue', ascending=False)

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

## Merging DataFrames

In [18]:

product_data = {
    'Product': ['A', 'B', 'C'],
    'Category': ['Electronics', 'Furniture', 'Appliances']
}

df_products = pd.DataFrame(product_data)
df_products

  Product     Category
0       A  Electronics
1       B    Furniture
2       C   Appliances

In [19]:

df_merged = pd.merge(df_sales, df_products, on='Product')
df_merged

  Product Region  Units_Sold  Price  Revenue     Category
0       A  North          10    100     1000  Electronics
1       B  South          15    200     3000    Furniture
2       C   East          20    150     3000   Appliances
3       A   West           5    100      500  Electronics
4       B  North          10    200     2000    Furniture
5       C  South          15    150     2250   Appliances
6       A   East          10    100     1000  Electronics
7       B   West           5    200     1000    Furniture
8       C  North          15    150     2250   Appliances

In [20]:

df_merged.groupby('Category')['Revenue'].sum()

Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64